server:
  port: 8080
# spring:
#   security:
#     user:
#       # name: user
#       # password: 1111
spring:
  datasource:
    url: jdbc:h2:mem:testdb;mode=MySQL;
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
